# -*- coding: utf-8 -*-
"""47_CYSE_Exp3_Vinayak_Vilaspure

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYAPY-Eqm6Q1v6VuqD618FvGTll8A6WG

**Vinayak Vilaspure | B.Tech Cyber Security | 22UF17258CS060**
```
AI-ML in Healthcare [Honours] 2025-26
Experiment 3: AI for Medical Diagnosis based on MRI/X-ray Data

```

#Kaggle API
"""

! pip install -q kaggle
from google.colab import files
files.upload()
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets download -d pcbreviglieri/pneumonia-xray-images

!pip install tensorflow

import zipfile

zf = "/content/pneumonia-xray-images.zip"
target_dir = "/content/dataset/cnn/pneumonia_revamped"

zfile = zipfile.ZipFile(zf)
zfile.extractall(target_dir)

"""# 1 Set up"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""## 1.1 Define Constants"""

train_path = '/content/dataset/cnn/pneumonia_revamped/train'
test_path = '/content/dataset/cnn/pneumonia_revamped/test'
valid_path = '/content/dataset/cnn/pneumonia_revamped/val'

#Define standard parameter values
batch_size = 16
img_height = 500
img_width = 500

"""# 2 Preparing Data

## 2.2 Image Data Augmentation
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img

image_gen = ImageDataGenerator(
                                   rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True,

                               )

test_data_gen = ImageDataGenerator(rescale = 1./255)



train = image_gen.flow_from_directory(
    train_path,
    target_size=(img_height, img_width),
    color_mode='grayscale',
    class_mode='binary',
    batch_size=batch_size
                                      )

test = test_data_gen.flow_from_directory(
      test_path,
      target_size=(img_height, img_width),
      color_mode='grayscale',shuffle=False,
      class_mode='binary',
      batch_size=batch_size
      )
valid = test_data_gen.flow_from_directory(
      valid_path,
      target_size=(img_height, img_width),
      color_mode='grayscale',
      class_mode='binary',
      batch_size=batch_size
      )

type(train)

plt.figure(figsize=(20, 12))
for i in range(0, 10):
    plt.subplot(2, 5, i+1)
    for X_batch, Y_batch in train:
        image = X_batch[0]
        dic = {0:'NORMAL', 1:'PNEUMONIA'}
        plt.title(dic.get(Y_batch[0]))
        plt.axis('off')
        plt.imshow(np.squeeze(image),cmap='gray',interpolation='nearest')
        break
plt.tight_layout()
plt.show()

"""### Define"""

featurewise_center=False,  # set input mean to 0 over the dataset
samplewise_center=False,  # set each sample mean to 0
featurewise_std_normalization=False,  # divide inputs by std of the dataset
samplewise_std_normalization=False,  # divide each input by its std
zca_whitening=False,  # apply ZCA whitening

rotation_range = 15,  # randomly rotate images in the range (degrees, 0 to 180)
zoom_range = 0.2, # Randomly zoom image
width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
horizontal_flip = True,  # randomly flip images
vertical_flip=False,# randomly flip images
shear_range=0.2,
brightness_range=(1.2, 1.5)

"""# 3 Tensorflow - Keras"""

from tensorflow.keras.models import Sequential,load_model,save_model
from tensorflow.keras.layers import Dense,Conv2D,Flatten,MaxPooling2D
from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau

"""## 3.1 Convolutional Neural Network Model"""

# let's build the CNN model

cnn = Sequential()

cnn.add(Conv2D(32, (3, 3), activation="relu", input_shape=(img_width, img_height, 1)))
cnn.add(MaxPooling2D(pool_size = (2, 2)))

cnn.add(Conv2D(32, (3, 3), activation="relu", input_shape=(img_width, img_height, 1)))
cnn.add(MaxPooling2D(pool_size = (2, 2)))

cnn.add(Conv2D(32, (3, 3), activation="relu", input_shape=(img_width, img_height, 1)))
cnn.add(MaxPooling2D(pool_size = (2, 2)))

cnn.add(Conv2D(64, (3, 3), activation="relu", input_shape=(img_width, img_height, 1)))
cnn.add(MaxPooling2D(pool_size = (2, 2)))

cnn.add(Conv2D(64, (3, 3), activation="relu", input_shape=(img_width, img_height, 1)))
cnn.add(MaxPooling2D(pool_size = (2, 2)))

cnn.add(Flatten())

cnn.add(Dense(activation = 'relu', units = 128))
cnn.add(Dense(activation = 'relu', units = 64))
cnn.add(Dense(activation = 'sigmoid', units = 1))


cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

cnn.summary()

!pip install pydot
from tensorflow.keras.utils import plot_model
plot_model(cnn,show_shapes=True, show_layer_names=True, rankdir='TB', expand_nested=True)

!pip install graphviz
from tensorflow.keras.utils import plot_model
plot_model(cnn,show_shapes=True, show_layer_names=True, rankdir='TB', expand_nested=True)

"""## 3.2 Fit Model"""

early = EarlyStopping(monitor="val_loss",
                      mode="min",
                      patience=3)

learning_rate_reduction = ReduceLROnPlateau(monitor='val_loss', patience = 2, verbose=1,factor=0.3, min_lr=0.000001)

callbacks_list = [ early, learning_rate_reduction]

from sklearn.utils.class_weight import compute_class_weight
weights = compute_class_weight(
                                        class_weight = "balanced",
                                        classes = np.unique(train.classes),
                                        y = train.classes
                                    )
cw = dict(zip( np.unique(train.classes), weights))
print(cw)

history = cnn.fit(train,epochs=1, validation_data=valid, class_weight=cw, callbacks=callbacks_list)

fp = "/content/cnn_pneu_vamp_model.h5"
cnn.save(fp)

cnn = load_model(fp)

#cnn.predict_segmentation()
preds=cnn.predict
pred=np.argmax(preds)
print(preds)
print(pred)

"""##3.3 Evaluation"""

pd.DataFrame(history.history).plot()

test_accu = cnn.evaluate(test)
print('The testing accuracy is :',test_accu[1]*100, '%')

preds = cnn.predict(test,verbose=1)

predictions = preds.copy()
predictions[predictions <= 0.5] = 0
predictions[predictions > 0.5] = 1

from sklearn.metrics import classification_report,confusion_matrix

cm = pd.DataFrame(data=confusion_matrix(test.classes, predictions, labels=[0, 1]),
                  index=["Actual Normal", "Actual Pneumonia"],
                  columns=["Predicted Normal", "Predicted Pneumonia"])
import seaborn as sns
sns.heatmap(cm,annot=True,fmt="d")

print(classification_report(y_true=test.classes, y_pred=predictions,
                            target_names =['NORMAL','PNEUMONIA']
 ))

test.reset()
x = np.concatenate([next(test)[0] for i in range(len(test))])
y = np.concatenate([next(test)[1] for i in range(len(test))])

print(x.shape)
print(y.shape)

dic = {0:'NORMAL', 1:'PNEUMONIA'}
plt.figure(figsize=(20,20))
for i in range(0+228, 9+228):
  plt.subplot(3, 3, (i-228)+1)
  if preds[i, 0] >= 0.5:
      out = ('{:.2%} probability of being Pneumonia case'.format(preds[i][0]))


  else:
      out = ('{:.2%} probability of being Normal case'.format(1-preds[i][0]))



  plt.title(out+"\n Actual case : "+ dic.get(y[i]))
  plt.imshow(np.squeeze(x[i]))
  plt.axis('off')
plt.show()

import plotly.graph_objects as go
fig = go.Figure( go.Scatter(y=y ) )
fig.show()

import plotly.graph_objects as go
fig = go.Figure( go.Scatter(y=predictions[:,0] ) )
fig.show()

# Testing with my own Chest X-Ray
hardik_path = '/content/dataset/cnn/pneumonia_revamped/test/normal/IM-0001-0001.jpeg'

from tensorflow.keras.preprocessing import image

hardik_img = image.load_img(hardik_path, target_size=(500, 500),color_mode='grayscale')

# Preprocessing the image
pp_hardik_img = image.img_to_array(hardik_img)
pp_hardik_img = pp_hardik_img/255
pp_hardik_img = np.expand_dims(pp_hardik_img, axis=0)

#predict
hardik_preds= cnn.predict(pp_hardik_img)

#print
plt.figure(figsize=(6,6))
plt.axis('off')
if hardik_preds>= 0.5:
    out = ('I am {:.2%} percent confirmed that this is a Pneumonia case'.format(hardik_preds[0][0]))

else:
    out = ('I am {:.2%} percent confirmed that this is a Normal case'.format(1-hardik_preds[0][0]))


plt.title("Hardik's Chest X-Ray\n"+out)
plt.imshow(np.squeeze(pp_hardik_img))
plt.show()

!pip install -q streamlit

!pip install h5py

"""Reset the execution environment after streamlit installation

## Download a streamlit app example

This example comes from [How to Build a Simple Machine Learning Web App in Python](https://www.youtube.com/watch?v=8M20LyCZDOY) and it will create a **Simple Iris Flower Prediction App**
"""

!wget https://raw.githubusercontent.com/smarthardik10/Medical-X-ray-Image-Classification-using-Convolutional-Neural-Network/main/webapp.py

"""## OR

## Install ngrok
"""

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

!unzip ngrok-stable-linux-amd64.zip

# Commented out IPython magic to ensure Python compatibility.
# %%writefile webapp.py
# import streamlit as st
# import numpy as np
# from PIL import Image
# from tensorflow.keras.models import load_model
# import tensorflow as tf
# 
# from tempfile import NamedTemporaryFile
# from tensorflow.keras.preprocessing import image
# 
# st.set_option('deprecation.showfileUploaderEncoding', False)
# @st.cache(allow_output_mutation=True)
# 
# def loading_model():
#   fp = "cnn_pneu_vamp_model.h5"
#   model_loader = load_model(fp)
#   return model_loader
# 
# cnn = loading_model()
# st.write("""
# # X-Ray Classification (Pneumonia/Normal)
# """)
# 
# 
# 
# 
# 
# 
# temp = st.file_uploader("Upload X-Ray Image")
# 
# buffer = temp
# temp_file = NamedTemporaryFile(delete=False)
# if buffer:
#     temp_file.write(buffer.getvalue())
#     st.write(image.load_img(temp_file.name))
# 
# 
# if buffer is None:
#   st.text("Oops! that doesn't look like an image. Try again.")
# 
# else:
# 
# 
# 
#   hardik_img = image.load_img(temp_file.name, target_size=(500, 500),color_mode='grayscale')
# 
#   # Preprocessing the image
#   pp_hardik_img = image.img_to_array(hardik_img)
#   pp_hardik_img = pp_hardik_img/255
#   pp_hardik_img = np.expand_dims(pp_hardik_img, axis=0)
# 
#   #predict
#   hardik_preds= cnn.predict(pp_hardik_img)
#   if hardik_preds>= 0.5:
#     out = ('I am {:.2%} percent confirmed that this is a Pneumonia case'.format(hardik_preds[0][0]))
# 
#   else:
#     out = ('I am {:.2%} percent confirmed that this is a Normal case'.format(1-hardik_preds[0][0]))
# 
#   st.success(out)
# 
#   image = Image.open(temp)
#   st.image(image,use_column_width=True)
# 
# 
# 
# 
# 
# 
#

get_ipython().system_raw('./ngrok http 8501 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c \'import sys, json; print("Execute the next cell and the go to the following URL: " +json.load(sys.stdin)["tunnels"][0]["public_url"])'

!streamlit run /content/webapp.py